### ISSUE TITLE
[Bug] German radio backpacks can be put Into the arsenal when you have them as backpack and select another one.

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#100] opened 2019-08-10 14:38 UTC
German radio backpacks can NOT be put into the arsenal when they are in a car/crate and transfer them. Then they vanish.

**Comment by Spoffy** [comment] 2019-08-13 17:12
Duplicate of #99

**Comment by SonorousMeerkat** [comment] 2019-08-15 18:24
This expands to include US and probably SOV ones as well. just the radio packs though...

**Comment by Spoffy** [comment] 2019-08-25 22:24
Fixed in 9895f548fa7b4595577f68c571e8cde560ebb85b

**Closed** 2019-08-25 22:24 UTC
Labels: bug
